//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dbo_RecipeEntities5 : DbContext
    {
        public Dbo_RecipeEntities5()
            : base("name=Dbo_RecipeEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_CATEGORIES> TBL_CATEGORIES { get; set; }
        public virtual DbSet<TBL_COMMENTS> TBL_COMMENTS { get; set; }
        public virtual DbSet<TBL_FOODS> TBL_FOODS { get; set; }
        public virtual DbSet<TBL_RECIPES> TBL_RECIPES { get; set; }
        public virtual DbSet<TBL_MESSAGES> TBL_MESSAGES { get; set; }
    }
}
