//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATEGORIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CATEGORIES()
        {
            this.TBL_FOODS = new HashSet<TBL_FOODS>();
        }
    
        public short ID { get; set; }
        public string NAME { get; set; }
        public Nullable<short> QUANTITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FOODS> TBL_FOODS { get; set; }
    }
}
