//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MESSAGES
    {
        public short ID { get; set; }
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public string MAIL { get; set; }
        public string MESSAGE { get; set; }
    }
}
