//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FOODS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FOODS()
        {
            this.TBL_COMMENTS = new HashSet<TBL_COMMENTS>();
        }
    
        public short ID { get; set; }
        public string NAME { get; set; }
        public string INGREDIENTS { get; set; }
        public string METHOD { get; set; }
        public string IMAGE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<byte> POINT { get; set; }
        public Nullable<short> CATEGORYID { get; set; }
        public Nullable<bool> STATE { get; set; }
    
        public virtual TBL_CATEGORIES TBL_CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_COMMENTS> TBL_COMMENTS { get; set; }
    }
}
