//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RECIPES
    {
        public short ID { get; set; }
        public string NAME { get; set; }
        public string INGREDIENTS { get; set; }
        public string METHOD { get; set; }
        public string IMAGE { get; set; }
        public string OWNER { get; set; }
        public string MAIL { get; set; }
        public Nullable<bool> STATE { get; set; }
    }
}
